### ISSUE TITLE
Containerizing Components

### ISSUE THREAD

**Issue by jordanwillis** [Tolli123/prj-rev-bwfs-dasmoto#1]
Very nice job on what I have reviewed so far!

One thing that I always recommend to students is to wrap your various page components in containers, where a component is 2 or more elements that work together to form one logical piece of your website.  Which in fact you did a very good job doing in on this project!

https://github.com/Tolli123/prj-rev-bwfs-dasmoto/blob/074eb490974cba80b06ef16a19f0f643e8fb7598/DasmotosArtsCrafts/index.html#L18-L23

On this project, there are really 3 main components, an item listing that is replicated 3 times (e.g. really it's just one component that gets used 3 different times).  So applying this containerization principle looks exactly like what you did with your paint, brushes, and and frames section.  

As I said, you had the foresight to already do this, which is great!  The only thing different that I would recommend is to consider using a single class name for each component, since each section is the same abstract thing (e.g. a product listing) that is just used for 3 different instances (e.g. 3 different products).  Therefore, you would end up with something like this instead.

``` html
<div class="item">
  <h2 id="brush">Brushes</h2>
  <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg"/>
  <h3>Hacksaw Brushes</h3>
  <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="price">Starting at $3.00 / brush.</span></p>
</div>

<div class="item">
  <h2 id="frame">Frames</h2>
  <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/frames.jpeg"/>
  <h3>Art Frames (assorted)</h3>
  <p>Assorted frames made of different material, including MDF, birchwood, and PDE. Select frames can be sanded and painted according to your needs. <span class="price">Starting at $2.00 / frame.</span></p>
</div>

<div class="item">
  <h2 id="paint">Paint</h2>
  <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/finnish.jpeg"/>
  <h3>Clean Finnish Paint</h3>
  <p>Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.). Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork. <span class="price">Starting at $5.00 / tube.</span>
</div>
```

The reason containerization is important is because 9 times our of 10 you will be referring to the component as a whole either in your CSS or JavaScript, so it's good to provide a simple way to do that (e.g. via it's parent container).  The other reason this is good is that it makes your HTML more semantic by highlighting through the actual structure that these groups of elements are working together in a logical way.

By using the same class name (e.g. again since we are dealing with the same component), it allows for a bit simpler CSS (primarily the selectors).

``` css
h1, 
h2, 
h3, 
p {
  font-family: "Helvetica", sans-serif;
}

h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
  font-size: 100px;
  color: khaki;
}

.item h2 {
  font-size: 32px;
  color: white;
}

.price {
  font-weight: bold;
  color: blue;
}

#brush {
  background-color: mediumspringgreen;
}

#frame {
  background-color: lightcoral;
}

#paint {
  background-color: skyblue;
}
```
