### ISSUE TITLE
Components with a single element

### ISSUE THREAD

**Issue by jordanwillis** [Tolli123/prj-rev-bwfs-dasmoto#3]
One other thing to watch out for is the temptation to create a container when it would only contain a single element.

https://github.com/Tolli123/prj-rev-bwfs-dasmoto/blob/074eb490974cba80b06ef16a19f0f643e8fb7598/DasmotosArtsCrafts/index.html#L12-L14

Doing this doesn't really bring you any benefit and in fact it typically results in more complicated CSS as well as bloated/unnecessary HTML code.  In this case, it would be better to just drop the container all together and let the heading stand on its own.

``` html
<body>

  <h1>Dasmoto's Arts & Crafts</h1>

  <div class="item">
    <h2 id="brush">Brushes</h2>
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/hacksaw.jpeg"/>
    <h3>Hacksaw Brushes</h3>
    <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="price">Starting at $3.00 / brush.</span></p>
  </div>

<!-- rest of code here -->
```

You can also see how our CSS selector is less complex now.

https://github.com/Tolli123/prj-rev-bwfs-dasmoto/blob/074eb490974cba80b06ef16a19f0f643e8fb7598/DasmotosArtsCrafts/resources/css/style.css#L54-L56
vs.
``` css
h1 {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
  font-size: 100px;
  color: khaki;
}
```

In case you don't want to use a selector for the heading element itself, then you can just add a class or ID attribute to your heading like this.

``` html
<h1 id="desmototitle">Dasmoto's Arts & Crafts</h1>
```

And then your selector would be...

``` css
#desmototitle {
  background-image: url("https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/pattern.jpeg");
  text-align: center;
  font-size: 100px;
  color: khaki;
}
```
